# Generated by Django 6.0.5 on 2026-07-12 11:47

import django.db.models.deletion
import markdownx.models
import portfolio.core.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in the post list.', verbose_name='excerpt')),
                ('content', markdownx.models.MarkdownxField(verbose_name='content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=portfolio.core.utils.FilenameGenerator('blogs/featured'), verbose_name='featured image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'blog post',
                'verbose_name_plural': 'blog posts',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', 'published_at'], name='blogs_blogp_status_ca12a6_idx')],
            },
        ),
    ]
