# Generated by Django 6.0.7 on 2026-07-27 00:53

import django.contrib.postgres.fields
import portfolio.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('role', models.CharField(help_text='e.g. Fullstack Engineer, Lead Engineer', max_length=200, verbose_name='role')),
                ('description', models.TextField(verbose_name='description')),
                ('project_url', models.URLField(blank=True, help_text='External link to the project', verbose_name='project URL')),
                ('tech_stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of technologies used', verbose_name='tech stack')),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or thumbnail', null=True, upload_to=portfolio.core.utils.FilenameGenerator('projects'), verbose_name='image')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('is_visible', models.BooleanField(db_index=True, default=True, verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('position', '-created_at'),
            },
        ),
    ]
