# Generated by Django 6.0.7 on 2026-07-27 05:51

import django.db.models.deletion
import portfolio.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.core.utils.FilenameGenerator('projects'), verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('position', models.PositiveIntegerField(db_index=True, default=0, verbose_name='position')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'project image',
                'verbose_name_plural': 'project images',
                'ordering': ('position', 'uploaded_at'),
            },
        ),
    ]
