# Generated by Django 6.0.7 on 2026-07-25 10:05

import django.db.models.deletion
import portfolio.apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('group', models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('triathlon', 'Triathlon'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Event categories',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('result_type', models.CharField(choices=[('time', 'Time-based'), ('score', 'Score-based'), ('placement', 'Placement only')], default='time', max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('finish_time', models.DurationField(blank=True, null=True)),
                ('overall_position', models.PositiveIntegerField(blank=True, null=True)),
                ('category_position', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=100)),
                ('bib_number', models.CharField(blank=True, max_length=20)),
                ('strava_url', models.URLField(blank=True)),
                ('official_result_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=portfolio.apps.events.models.event_photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as the main thumbnail for this event')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['-is_cover', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date'], name='events_even_date_13e470_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_even_categor_25d9bd_idx'),
        ),
    ]
