# Generated by Django 6.0.5 on 2026-07-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pace_per_km',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='typical_distance_km',
        ),
        migrations.AddField(
            model_name='event',
            name='strava_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='group',
            field=models.CharField(choices=[('running', 'Running'), ('cycling', 'Cycling'), ('triathlon', 'Triathlon'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
