# Generated by Django 6.0.7 on 2026-07-25 10:45

from django.db import migrations, models
from django.utils.text import slugify


def backfill_event_slugs(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for event in Event.objects.all():
        slug = slugify(event.name)
        existing = Event.objects.filter(slug=slug).exclude(pk=event.pk)
        if existing.exists():
            slug = f"{event.pk}-{slug}"
        event.slug = slug
        event.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.CharField(max_length=50, blank=True, null=True),
        ),
        migrations.RunPython(backfill_event_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
